name:                smarties
version:             '1.0.2'
github:              "pdlla/smarties"
license:             BSD3
author:              "pdlla"
maintainer:          "chippermonky@gmail.com"
copyright:           "2018 Peter Lu"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis: Haskell Behavior Tree Library
category: Games
description:         Please see the README on Github at <https://github.com/githubuser/smarties#readme>

dependencies:
- base >= 4.7 && < 5.0
- mtl
- QuickCheck >= 2.11
- random
- lens
- MonadRandom
- monadplus
- text

ghc-options:
- -Wall
- -Wcompat
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wredundant-constraints
#- -Werror

default-extensions:
- InstanceSigs
- LambdaCase
- GADTs
- TupleSections
- ScopedTypeVariables
- FlexibleInstances
- MultiParamTypeClasses
- TemplateHaskell

library:
  source-dirs: src
  exposed-modules:
    - Smarties
    - Smarties.Trans

executables:
  pronouns:
    main:                Main.hs
    source-dirs:         examples/pronouns
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - smarties

  tutorial:
    main:                Main.hs
    source-dirs:         examples/tutorial
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - smarties
    - ilist
    - vector

  slimes:
    main:                Main.hs
    source-dirs:         examples/slimes
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - smarties
    - ilist
    - vector
    - haskeline


tests:
  smarties-test:
    main:                Spec.hs
    source-dirs:         test/unit
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - smarties
    - hspec
